# Generated by Django 5.0.3 on 2024-06-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='official_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Contact_no', models.CharField(max_length=100, unique=True)),
                ('Province', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Local_government', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='farmer', max_length=100)),
                ('identity_proof', models.ImageField(upload_to='pending_official_requests')),
            ],
        ),
    ]
