# Generated by Django 5.0.3 on 2024-06-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_official_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identity_proof',
            field=models.ImageField(upload_to='proof_document/'),
        ),
        migrations.AlterField(
            model_name='official_requests',
            name='identity_proof',
            field=models.ImageField(upload_to='pending_official_requests/'),
        ),
    ]
