# Generated by Django 5.0.3 on 2024-06-19 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_identity_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='official_requests',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
