# Generated by Django 5.0.3 on 2024-06-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_official_requests_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official_requests',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Farmer', 'FARMER'), ('Official', 'Official')], default='Farmer', max_length=10),
        ),
    ]
