# Generated by Django 5.0.6 on 2024-06-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_official_requests_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='official_requests',
            name='password',
            field=models.CharField(default='<PASSWORD>', max_length=100),
        ),
    ]
