# Generated by Django 5.0.6 on 2024-06-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='official_requests',
            name='email',
            field=models.EmailField(default='none', max_length=100),
        ),
    ]
