# Generated by Django 5.0.6 on 2024-07-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_submission',
            name='sent_in_phone',
            field=models.BooleanField(default=False),
        ),
    ]
