# Generated by Django 5.0.6 on 2024-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_publishing', '0002_alter_scoreboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_submission',
            name='notice_title',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
